# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in tailmix-ui.gemspec
gemspec

# Local development path for tailmix engine
gem "tailmix", path: "../"

gem "irb"
gem "rake", "~> 13.0"
gem "rspec", "~> 3.0"
